"""
tests/ai_validation/test_payment_ai_generated.py
 
AI-Generated Payment Validation Test Suite
============================================
Generated by: FinFlow AI Quality Platform (Groq LLM — llama-3.1)
Requirements source: data/requirements/payment_requirements.txt
Human review: Fixed mock service logic and test data issues
 
Day 1 — AI-Enabled Test Engineering demonstration
"""
 
import uuid
import pytest
from datetime import datetime, timedelta
 
VALID_CURRENCIES = ["USD", "GBP", "EUR", "JPY", "CHF", "AUD", "CAD", "HKD"]
 
# Module-level store for idempotency keys — persists across tests
_processed_payments = {}
 
 
@pytest.fixture(autouse=True)
def clear_idempotency_store():
    """Clear idempotency store before each test for isolation."""
    _processed_payments.clear()
    yield
    _processed_payments.clear()
 
 
@pytest.fixture
def mock_payment_service():
    """
    Mock payment service simulating real payment API behaviour.
    Validates: amount, currency, customer_id, idempotency, settlement dates.
    Fixed: uuid import, type checking, parameter handling, test data.
    """
    def _service(
        amount=None,
        currency=None,
        customer_id=None,
        idempotency_key=None,
        settlement_date=None,
        transaction_date=None
    ):
        # ── Idempotency check ─────────────────────────────────────────────
        if idempotency_key and idempotency_key in _processed_payments:
            return _processed_payments[idempotency_key]
 
        # ── Amount validation ─────────────────────────────────────────────
        if amount is None:
            return {"result": "Payment rejected", "error_code": "MISSING_AMOUNT"}
 
        if isinstance(amount, str):
            if amount == "":
                return {"result": "Payment rejected", "error_code": "MISSING_AMOUNT"}
            try:
                amount = float(amount)
            except ValueError:
                return {"result": "Payment rejected", "error_code": "INVALID_AMOUNT"}
 
        if amount < 0:
            return {"result": "Payment rejected", "error_code": "NEGATIVE_AMOUNT"}
 
        if amount == 0 or amount < 0.01 or amount > 999999.99:
            return {"result": "Payment rejected", "error_code": "INVALID_AMOUNT"}
 
        # ── Currency validation ───────────────────────────────────────────
        if currency is None:
            return {"result": "Payment rejected", "error_code": "INVALID_CURRENCY"}
 
        if not isinstance(currency, str) or len(currency) != 3:
            return {"result": "Payment rejected", "error_code": "INVALID_CURRENCY"}
 
        if currency.upper() not in VALID_CURRENCIES:
            return {"result": "Payment rejected", "error_code": "INVALID_CURRENCY"}
 
        # ── Customer ID validation ────────────────────────────────────────
        if not customer_id:
            return {"result": "Payment rejected", "error_code": "MISSING_CUSTOMER"}
 
        try:
            uuid.UUID(str(customer_id))
        except (ValueError, AttributeError):
            return {"result": "Payment rejected", "error_code": "MISSING_CUSTOMER"}
 
        # ── Settlement date validation ────────────────────────────────────
        if transaction_date and settlement_date:
            try:
                tx_dt  = datetime.strptime(transaction_date, "%Y-%m-%d")
                set_dt = datetime.strptime(settlement_date, "%Y-%m-%d")
                if set_dt < tx_dt:
                    return {
                        "result":     "Payment rejected",
                        "error_code": "INVALID_SETTLEMENT_DATE"
                    }
                if (set_dt - tx_dt).days > 5:
                    return {
                        "result":     "Payment rejected",
                        "error_code": "INVALID_SETTLEMENT_DATE"
                    }
            except ValueError:
                return {"result": "Payment rejected", "error_code": "INVALID_SETTLEMENT_DATE"}
 
        # Default settlement date = transaction_date + 1 day
        if settlement_date is None and transaction_date:
            tx_dt = datetime.strptime(transaction_date, "%Y-%m-%d")
            settlement_date = (tx_dt + timedelta(days=1)).strftime("%Y-%m-%d")
 
        # ── Success ───────────────────────────────────────────────────────
        payment_id = str(uuid.uuid4())
        result = {
            "result":          "Payment processed successfully",
            "payment_id":      payment_id,
            "amount":          amount,
            "currency":        currency.upper(),
            "settlement_date": settlement_date,
            "error_code":      None
        }
 
        # Store for idempotency
        if idempotency_key:
            _processed_payments[idempotency_key] = {
                "result":     "Original payment response returned",
                "payment_id": payment_id,
                "error_code": None
            }
 
        return result
 
    return _service
 
 
# ── Helpers ────────────────────────────────────────────────────────────────────
 
def valid_customer_id():
    """Return a valid UUID customer ID for use in tests."""
    return "123e4567-e89b-12d3-a456-426614174000"
 
def valid_payment(mock, **overrides):
    """Return a minimal valid payment — override individual fields as needed."""
    defaults = {
        "amount":      100.00,
        "currency":    "GBP",
        "customer_id": valid_customer_id(),
    }
    defaults.update(overrides)
    return mock(**defaults)
 
 
# ══════════════════════════════════════════════════════════════════════════════
# REQ-001: Payment Amount Validation
# ══════════════════════════════════════════════════════════════════════════════
 
class TestREQ001:
 
    @pytest.mark.parametrize("amount", [0.01, 10.99, 500.00, 999999.99])
    def test_TS_001_ValidPaymentAmount(self, mock_payment_service, amount):
        """Valid amounts between £0.01 and £999,999.99 are accepted."""
        result = valid_payment(mock_payment_service, amount=amount)
        assert result["result"] == "Payment processed successfully", \
            f"Expected success for amount={amount}, got: {result}"
        assert result["error_code"] is None
 
    def test_TS_002_PaymentAmountBelowMinimum(self, mock_payment_service):
        """Amount below £0.01 is rejected with INVALID_AMOUNT."""
        result = mock_payment_service(amount=0.001)
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "INVALID_AMOUNT"
 
    def test_TS_003_PaymentAmountAboveMaximum(self, mock_payment_service):
        """Amount above £999,999.99 is rejected with INVALID_AMOUNT."""
        result = mock_payment_service(amount=1_000_000.00)
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "INVALID_AMOUNT"
 
    def test_TS_004_NullPaymentAmount(self, mock_payment_service):
        """Null amount is rejected with MISSING_AMOUNT."""
        result = mock_payment_service(amount=None)
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "MISSING_AMOUNT"
 
    def test_TS_005_EmptyPaymentAmount(self, mock_payment_service):
        """Empty string amount is rejected with MISSING_AMOUNT."""
        result = mock_payment_service(amount="")
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "MISSING_AMOUNT"
 
    def test_TS_006_NegativePaymentAmount(self, mock_payment_service):
        """Negative amount is rejected with NEGATIVE_AMOUNT."""
        result = mock_payment_service(amount=-10.99)
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "NEGATIVE_AMOUNT"
 
    def test_TS_006b_ZeroPaymentAmount(self, mock_payment_service):
        """Zero amount is rejected with INVALID_AMOUNT."""
        result = mock_payment_service(amount=0)
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "INVALID_AMOUNT"
 
 
# ══════════════════════════════════════════════════════════════════════════════
# REQ-002: Currency Code Validation
# ══════════════════════════════════════════════════════════════════════════════
 
class TestREQ002:
 
    @pytest.mark.parametrize("currency", ["USD", "GBP", "EUR", "JPY", "CHF"])
    def test_TS_007_ValidCurrencyCode(self, mock_payment_service, currency):
        """Valid ISO currency codes are accepted."""
        result = valid_payment(mock_payment_service, currency=currency)
        assert result["result"] == "Payment processed successfully", \
            f"Expected success for currency={currency}"
        assert result["error_code"] is None
 
    def test_TS_008_InvalidCurrencyCode(self, mock_payment_service):
        """Invalid currency code ABC is rejected with INVALID_CURRENCY."""
        result = valid_payment(mock_payment_service, currency="ABC")
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "INVALID_CURRENCY"
 
    @pytest.mark.parametrize("currency", ["usd", "gbp", "Eur"])
    def test_TS_009_CurrencyCodeCaseInsensitive(self, mock_payment_service, currency):
        """Currency codes are case-insensitive — lowercase accepted."""
        result = valid_payment(mock_payment_service, currency=currency)
        assert result["result"] == "Payment processed successfully", \
            f"Expected success for lowercase currency={currency}"
 
    def test_TS_010_CurrencyCodeTooShort(self, mock_payment_service):
        """Currency code shorter than 3 chars is rejected."""
        result = valid_payment(mock_payment_service, currency="US")
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "INVALID_CURRENCY"
 
    def test_TS_010b_CurrencyCodeTooLong(self, mock_payment_service):
        """Currency code longer than 3 chars is rejected."""
        result = valid_payment(mock_payment_service, currency="USDD")
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "INVALID_CURRENCY"
 
    def test_TS_010c_NullCurrencyCode(self, mock_payment_service):
        """Null currency code is rejected with INVALID_CURRENCY."""
        result = valid_payment(mock_payment_service, currency=None)
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "INVALID_CURRENCY"
 
 
# ══════════════════════════════════════════════════════════════════════════════
# REQ-003: Payment Idempotency
# ══════════════════════════════════════════════════════════════════════════════
 
class TestREQ003:
 
    def test_TS_011_UniqueIdempotencyKey(self, mock_payment_service):
        """First submission with a new idempotency key succeeds."""
        result = valid_payment(
            mock_payment_service,
            idempotency_key="unique-key-001"
        )
        assert result["result"] == "Payment processed successfully"
        assert result["error_code"] is None
 
    def test_TS_012_DuplicateIdempotencyKey(self, mock_payment_service):
        """Second submission with same key returns original response."""
        # First submission
        first = valid_payment(
            mock_payment_service,
            idempotency_key="duplicate-key-001"
        )
        assert first["result"] == "Payment processed successfully"
 
        # Duplicate submission — must return original, not process again
        duplicate = valid_payment(
            mock_payment_service,
            idempotency_key="duplicate-key-001"
        )
        assert duplicate["result"] == "Original payment response returned"
        assert duplicate["payment_id"] == first["payment_id"], \
            "Duplicate must return same payment_id as original"
 
    def test_TS_012b_DifferentKeysAreIndependent(self, mock_payment_service):
        """Different idempotency keys produce independent payments."""
        result1 = valid_payment(mock_payment_service, idempotency_key="key-A")
        result2 = valid_payment(mock_payment_service, idempotency_key="key-B")
        assert result1["result"] == "Payment processed successfully"
        assert result2["result"] == "Payment processed successfully"
        assert result1["payment_id"] != result2["payment_id"]
 
 
# ══════════════════════════════════════════════════════════════════════════════
# REQ-004: Settlement Date Rules
# ══════════════════════════════════════════════════════════════════════════════
 
class TestREQ004:
 
    def test_TS_013_ValidSettlementDate(self, mock_payment_service):
        """Settlement date same as transaction date is valid (T+0)."""
        result = valid_payment(
            mock_payment_service,
            transaction_date="2024-09-20",
            settlement_date="2024-09-20"
        )
        assert result["result"] == "Payment processed successfully"
        assert result["error_code"] is None
 
    def test_TS_013b_SettlementTPlus2Valid(self, mock_payment_service):
        """Settlement date T+2 is valid."""
        result = valid_payment(
            mock_payment_service,
            transaction_date="2024-09-20",
            settlement_date="2024-09-22"
        )
        assert result["result"] == "Payment processed successfully"
 
    def test_TS_014_SettlementBeforeTransaction(self, mock_payment_service):
        """Settlement date before transaction date is rejected."""
        result = valid_payment(
            mock_payment_service,
            transaction_date="2024-09-20",
            settlement_date="2024-09-15"
        )
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "INVALID_SETTLEMENT_DATE"
 
    def test_TS_015_SettlementMoreThan5Days(self, mock_payment_service):
        """Settlement date more than 5 days after transaction is rejected."""
        result = valid_payment(
            mock_payment_service,
            transaction_date="2024-09-20",
            settlement_date="2024-09-27"
        )
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "INVALID_SETTLEMENT_DATE"
 
    def test_TS_016_NullSettlementDefaultsToTPlusOne(self, mock_payment_service):
        """Null settlement date defaults to transaction_date + 1 day."""
        result = valid_payment(
            mock_payment_service,
            transaction_date="2024-09-20",
            settlement_date=None
        )
        assert result["result"] == "Payment processed successfully"
        assert result["settlement_date"] == "2024-09-21"
 
 
# ══════════════════════════════════════════════════════════════════════════════
# REQ-005: Customer ID Validation
# ══════════════════════════════════════════════════════════════════════════════
 
class TestREQ005:
 
    def test_TS_017_ValidCustomerID(self, mock_payment_service):
        """Valid UUID customer_id is accepted."""
        result = valid_payment(
            mock_payment_service,
            customer_id="123e4567-e89b-12d3-a456-426614174000"
        )
        assert result["result"] == "Payment processed successfully"
        assert result["error_code"] is None
 
    def test_TS_017b_AnotherValidUUID(self, mock_payment_service):
        """Any valid UUID format is accepted."""
        result = valid_payment(
            mock_payment_service,
            customer_id=str(uuid.uuid4())
        )
        assert result["result"] == "Payment processed successfully"
 
    def test_TS_018_InvalidCustomerID(self, mock_payment_service):
        """Non-UUID customer_id is rejected with MISSING_CUSTOMER."""
        result = mock_payment_service(
            amount=100.00,
            currency="GBP",
            customer_id="invalid_id"
        )
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "MISSING_CUSTOMER"
 
    def test_TS_019_NullCustomerID(self, mock_payment_service):
        """Null customer_id is rejected with MISSING_CUSTOMER."""
        result = mock_payment_service(
            amount=100.00,
            currency="GBP",
            customer_id=None
        )
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "MISSING_CUSTOMER"
 
    def test_TS_020_EmptyCustomerID(self, mock_payment_service):
        """Empty string customer_id is rejected with MISSING_CUSTOMER."""
        result = mock_payment_service(
            amount=100.00,
            currency="GBP",
            customer_id=""
        )
        assert result["result"] == "Payment rejected"
        assert result["error_code"] == "MISSING_CUSTOMER"
 